### ISSUE TITLE
Careful with the repo name

### ISSUE THREAD

**Issue by fireproofsocks** [StanXian/Project-no.1#2]
It's not a big deal for this project, but it's a good habit to use only lower-case letters and underscores for your repository names.  The reason I suggest this is because if you ever want to publish a package, there are usually naming restrictions (e.g. for python modules).  Just food for thought.

**Comment by BSkedgell** [comment]
@StanXian can you edit the repo name to follow the issues outlined here

**Comment by BSkedgell** [comment]
Stan edited the repo name
